name       : jpegoptim
version    : 1.4.6
release    : 3
source     :
    - https://github.com/tjko/jpegoptim/archive/RELEASE.1.4.6.tar.gz : c44dcfac0a113c3bec13d0fc60faf57a0f9a31f88473ccad33ecdf210b4c0c52
license    : GPL-2.0-or-later
component  : system.utils
summary    : Utility to optimize jpeg files.
description: |
    Provides lossless optimization of jpeg files (based on optimizing the Huffman tables) and "lossy" optimization based on setting maximum quality factor.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
