name       : jpegoptim
version    : 1.4.4
release    : 1
source     :
    - https://github.com/tjko/jpegoptim/archive/RELEASE.1.4.4.tar.gz : bc6b018ae8c3eb12d07596693d54243e214780a2a2303a6578747d3671f45da3
license    : GPL-2.0
component  : system.utils
summary    : Utility to optimize jpeg files.
description: |
    Provides lossless optimization of jpeg files (based on optimizing the Huffman tables) and "lossy" optimization based on setting maximum quality factor.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
